// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DBError() {
  return window['go']['app']['App']['DBError']();
}

export function GetStatus(arg1) {
  return window['go']['app']['App']['GetStatus'](arg1);
}

export function ListPrinters() {
  return window['go']['app']['App']['ListPrinters']();
}

export function Models() {
  return window['go']['app']['App']['Models']();
}

export function ResetWaste(arg1) {
  return window['go']['app']['App']['ResetWaste'](arg1);
}
