// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function DBError():Promise<string>;

export function GetStatus(arg1:string):Promise<app.StatusView>;

export function ListPrinters():Promise<Array<app.PrinterInfo>>;

export function Models():Promise<Array<string>>;

export function ResetWaste(arg1:string):Promise<string>;
